---
name: CI (master)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  unit_tests:
    name: Unit tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: Adzz/jest_test_action@v1.0.0
        env:
          API_KEY: ${{ secrets.API_KEY }}
        with:
          package-manager: npm
          command: test
  functional_tests:
    name: Functional tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Create bin
        uses: ./
        id: jsonbin_create
        with:
          body: '{"running_by":"${{ github.actor }}"}'
          method: 'CREATE'
          api_key: ${{ secrets.API_KEY }}
      - name: Validate output
        run: |
          [[ $(expr length "${{ steps.jsonbin_create.outputs.bin_id }}") -eq 0 ]] && exit 1;
          [[ "${{ steps.jsonbin_create.outputs.url }}" == "https://api.jsonbin.io/b/${{ steps.jsonbin_create.outputs.bin_id }}" ]] || exit 1;
      - name: Call URL that was returned
        uses: fjogeleit/http-request-action@v1.1.0
        id: http1
        with:
          url: '${{ steps.jsonbin_create.outputs.url }}'
          method: 'GET'
          customHeaders: '{"secret-key": "${{ secrets.API_KEY }}"}'
      - name: Validate response
        run: |
          [[ "${{ steps.http1.outputs.response }}" == '{"running_by":"${{ github.actor }}"}' ]] || exit 1;
      - name: Update bin
        uses: ./
        id: jsonbin_update
        with:
          body: '{"author":"${{ github.actor }}"}'
          method: 'UPDATE'
          bin_id: '${{ steps.jsonbin_create.outputs.bin_id }}'
          api_key: ${{ secrets.API_KEY }}
      - name: Call URL that was returned
        uses: fjogeleit/http-request-action@v1.1.0
        id: http2
        with:
          url: '${{ steps.jsonbin_update.outputs.url }}'
          method: 'GET'
          customHeaders: '{"secret-key": "${{ secrets.API_KEY }}"}'
      - name: Validate response
        run: |
          [[ "${{ steps.http2.outputs.response }}" == '{"author":"${{ github.actor }}"}' ]] || exit 1;
      - name: Delete bin
        uses: ./
        id: jsonbin_delete
        with:
          bin_id: '${{ steps.jsonbin_update.outputs.bin_id }}'
          method: 'DELETE'
          api_key: ${{ secrets.API_KEY }}
      - name: Validate URL does not exist
        run: |
          [[ $(curl -s -o /dev/null -w "%{http_code}" ${{ steps.jsonbin_update.outputs.url }}) -eq 404 ]] || exit 1;
